OPT_DEFS += -DSPLIT_TRANSACTION_IDS_USER='USER_SYNC_LIGHTS_A, USER_SYNC_LIGHTS_B, USER_KEY_COLORS_STARTUP'
SRC += key_colors.c

RAW_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes
VIAL_INSECURE = yes

ENCODER_MAP_ENABLE = yes

RGB_MATRIX_CUSTOM_USER = yes

# Debug
CONSOLE_ENABLE = no
