OPT_DEFS += -DSPLIT_TRANSACTION_IDS_USER=USER_SYNC_SIGNALRGB
SRC += signalrgb_split.c

RAW_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes
VIAL_INSECURE = yes

ENCODER_MAP_ENABLE = yes

# Debug
CONSOLE_ENABLE = no